
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <header>
          <h1>Sticker Shop</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
